# Generated by Django 5.1.3 on 2024-11-17 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_method',
        ),
    ]
