# Generated by Django 5.1.3 on 2024-11-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_remove_order_shipping_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
